## AWS S3 연동
cloud:
  aws:
    s3:
      bucket-name: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}
openai:
  api-key: ${OPENAI_API_KEY}
